### ISSUE TITLE
AttributeError: partially initialized module 'mkdocs_obsidian.common.config' has no attribute 'create_env'

### ISSUE THREAD

**Issue by simonmaris** [Mara-Li/mkdocs_obsidian_template#1]
I wanted to try this out - but ran into some problems. 

I clones this repo and created a pipenv for it and installed everything from requirements.txt. 
Firstly, `rich` seems to be missing from requirements.txt?
Secondly, this error happens on call obs2mk: 
`Traceback (most recent call last):
  File "/Users/simon/opt/anaconda3/envs/obs2mk/bin/obs2mk", line 5, in <module>
    from mkdocs_obsidian.__main__ import main
  File "/Users/simon/opt/anaconda3/envs/obs2mk/lib/python3.10/site-packages/mkdocs_obsidian/__main__.py", line 16, in <module>
    from mkdocs_obsidian.common import (
  File "/Users/simon/opt/anaconda3/envs/obs2mk/lib/python3.10/site-packages/mkdocs_obsidian/common/config.py", line 13, in <module>
    from mkdocs_obsidian.common import global_value as gl
  File "/Users/simon/opt/anaconda3/envs/obs2mk/lib/python3.10/site-packages/mkdocs_obsidian/common/global_value.py", line 26, in <module>
    config.create_env()
AttributeError: partially initialized module 'mkdocs_obsidian.common.config' has no attribute 'create_env' (most likely due to a circular import)`

I also tried everything in a conda env, same thing there.. Any ideas?

**Comment by Mara-Li** [comment]
I will check that ! Thank you for the report :)

**Comment by Mara-Li** [comment]
Please, inform me if the last update of the script repair this problem !
