### ISSUE TITLE
Can't run obs2mk on MacOS Monterey

### ISSUE THREAD

**Issue by suky57** [Mara-Li/mkdocs_obsidian_template#2]
Hello,

I'm not able to run the script on MacOS Monterey, following error occures:

```
martin@Martins-MacBook-Pro mkdocs_obsidian_template % obs2mk --h
Traceback (most recent call last):
  File "/Users/martin/Library/Python/3.8/bin//obs2mk", line 5, in <module>
    from mkdocs_obsidian.__main__ import main
  File "/Users/martin/Library/Python/3.8/lib/python/site-packages/mkdocs_obsidian/__main__.py", line 17, in <module>
    from mkdocs_obsidian.common import (
  File "/Users/martin/Library/Python/3.8/lib/python/site-packages/mkdocs_obsidian/common/global_value.py", line 14, in <module>
    from mkdocs_obsidian.common import config
  File "/Users/martin/Library/Python/3.8/lib/python/site-packages/mkdocs_obsidian/common/config.py", line 20, in <module>
    def pyto_environment(console) -> tuple[str, str]:
TypeError: 'type' object is not subscriptable
```

**Comment by suky57** [comment]
solved by using py3.9

**Comment by Mara-Li** [comment]
Thanks you ! I will update the requirements
